### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by SergeyBukhman** [state-machines/state_machines-graphviz#1]
Hey, I installed the gem and graphviz. Can't figure out how to make this work. In the old state_machine gem it was `rake state_machine:draw FILE=invoice.rb CLASS=Invoice` But I didn't even get a rake task with this. Does it work?

**Comment by rosskevin** [comment]
Agreed, from the old project, it appears that the tasks were never migrated.

**Comment by rosskevin** [comment]
I'm giving it a shot now.

**Comment by rosskevin** [comment]
@SergeyBukhman my pull request works.  https://github.com/state-machines/state_machines-graphviz/pull/2
