### ISSUE TITLE
Permissions request for rubygems

### ISSUE THREAD

**Issue by rosskevin** [state-machines/state_machines-graphviz#5]
@seuros - I'm trying to push #4 to https://rubygems.org/gems/state_machines-graphviz via `rake spec release`, but permissions aren't setup there.   My username there is `rosskevin` as well.

**Comment by rosskevin** [comment]
http://guides.rubygems.org/command-reference/#gem-owner

`gem owner state_machines-graphviz -k [redacted]`

**Comment by seuros** [comment]
You got it :smile_cat: . 

Thanks for raising the issue. i should not be the only one with push permissions to the gems.

**Comment by rosskevin** [comment]
Thanks, v0.0.2 pushed.
